import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Banknote, CheckCircle2, CreditCard, Loader2, ReceiptText, RefreshCw, WalletCards } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useOrganization } from "@/contexts/OrganizationContext";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const methodLabels: Record<string, string> = {
  pix: "PIX",
  cash: "Dinheiro",
  credit_card: "Cartão de crédito",
  debit_card: "Cartão de débito",
  voucher: "Vale",
};

export default function Finance() {
  const {organizationId}=useOrganization(); const queryClient=useQueryClient(); const {toast}=useToast();
  const [method,setMethod]=useState("pix");
  const orders=useQuery({
    queryKey:["finance-orders",organizationId],enabled:Boolean(organizationId&&supabase),
    queryFn:async()=>{const {data,error}=await supabase!.from("orders").select("id,created_at,total,payment_status,operational_status,customers(name),payments(id,amount,status,method,paid_at,created_at)").eq("organization_id",organizationId!).order("created_at",{ascending:false}).limit(100);if(error)throw error;return data;}
  });
  const pay=useMutation({
    mutationFn:async({id,amount,paymentMethod}:{id:string;amount:number;paymentMethod:string})=>{const {error}=await supabase!.rpc("record_payment",{p_order_id:id,p_method:paymentMethod,p_amount:amount});if(error)throw error;},
    onSuccess:async(_data,variables)=>{await Promise.all([queryClient.invalidateQueries({queryKey:["finance-orders",organizationId]}),queryClient.invalidateQueries({queryKey:["orders",organizationId]}),queryClient.invalidateQueries({queryKey:["business-dashboard",organizationId]})]);toast({title:"Pagamento registrado",description:`Forma: ${methodLabels[variables.paymentMethod] ?? variables.paymentMethod}.`});},
    onError:()=>toast({title:"Pagamento não registrado",description:"O valor foi rejeitado pelo servidor.",variant:"destructive"})
  });
  const list=orders.data??[]; const paid=list.filter(order=>order.payment_status==="paid"); const pending=list.filter(order=>order.payment_status!=="paid"&&order.operational_status!=="cancelled");
  const revenue=list.reduce((sum,order)=>sum+(order.payments??[]).filter(payment=>payment.status==="paid").reduce((value,payment)=>value+Number(payment.amount),0),0); const receivable=pending.reduce((sum,order)=>sum+(Number(order.total)-(order.payments??[]).filter(payment=>payment.status==="paid").reduce((value,payment)=>value+Number(payment.amount),0)),0);
  const recentPayments=list.flatMap(order=>(order.payments??[]).filter(payment=>payment.status==="paid").map(payment=>({ ...payment,orderId:order.id,customer:(order.customers as unknown as {name:string}|null)?.name??"Consumidor" }))).sort((a,b)=>new Date(b.paid_at??b.created_at).getTime()-new Date(a.paid_at??a.created_at).getTime()).slice(0,20);
  const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
  return <div className="min-h-screen bg-background p-4 md:p-8 lg:p-10"><div className="mx-auto max-w-7xl space-y-7">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-primary">Controle</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Financeiro</h1><p className="mt-1 text-muted-foreground">Registre recebimentos e acompanhe valores pendentes.</p></div><Button type="button" variant="outline" className="rounded-xl" disabled={orders.isFetching} onClick={()=>orders.refetch()}>{orders.isFetching?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}{orders.isFetching?"Atualizando…":"Atualizar dados"}</Button></div>
    {orders.isError&&<Card className="border-destructive/30 bg-destructive/5"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><AlertTriangle className="h-5 w-5 shrink-0 text-destructive"/><div className="flex-1"><p className="font-semibold">Não foi possível carregar o Financeiro</p><p className="text-sm text-muted-foreground">A conexão não respondeu corretamente. Tente novamente.</p></div><Button type="button" variant="outline" className="rounded-xl" onClick={()=>orders.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Tentar novamente</Button></CardContent></Card>}
    <div className="grid gap-4 sm:grid-cols-3"><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="flex items-center gap-2 text-sm text-muted-foreground"><Banknote className="h-4 w-4"/>Receita recebida</p><strong className="mt-2 block text-2xl text-emerald-700">{money.format(revenue)}</strong></CardContent></Card><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="flex items-center gap-2 text-sm text-muted-foreground"><ReceiptText className="h-4 w-4"/>A receber</p><strong className="mt-2 block text-2xl text-amber-700">{money.format(receivable)}</strong></CardContent></Card><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="flex items-center gap-2 text-sm text-muted-foreground"><CheckCircle2 className="h-4 w-4"/>Pedidos pagos</p><strong className="mt-2 block text-2xl">{paid.length}</strong></CardContent></Card></div>
    <Card className="surface-elevated rounded-2xl"><CardHeader className="gap-4 sm:flex-row sm:items-end sm:justify-between"><CardTitle className="text-xl">Pagamentos pendentes</CardTitle><div className="w-full space-y-1.5 sm:w-56"><Label>Forma do recebimento</Label><Select value={method} onValueChange={setMethod}><SelectTrigger className="w-full rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pix">PIX</SelectItem><SelectItem value="cash">Dinheiro</SelectItem><SelectItem value="credit_card">Cartão de crédito</SelectItem><SelectItem value="debit_card">Cartão de débito</SelectItem><SelectItem value="voucher">Vale</SelectItem></SelectContent></Select></div></CardHeader><CardContent>{orders.isLoading?<p className="py-12 text-center text-muted-foreground">Carregando…</p>:orders.isError?<p className="py-12 text-center text-muted-foreground">Os pagamentos não puderam ser exibidos.</p>:pending.length?<div className="space-y-3">{pending.map(order=>{const paidAmount=(order.payments??[]).filter(payment=>payment.status==="paid").reduce((sum,payment)=>sum+Number(payment.amount),0);const remaining=Number(order.total)-paidAmount;return <article key={order.id} className="flex flex-col gap-4 rounded-2xl border p-4 sm:flex-row sm:items-center"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><WalletCards className="h-5 w-5"/></span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><strong>#{order.id.slice(0,8)}</strong><Badge variant="outline">{order.payment_status==="partially_paid"?"Parcial":"Pendente"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{new Date(order.created_at).toLocaleString("pt-BR")} · {(order.customers as unknown as {name:string}|null)?.name??"Consumidor"}</p></div><div className="sm:text-right"><p className="text-xs text-muted-foreground">Saldo</p><strong className="text-lg text-primary">{money.format(remaining)}</strong></div><Button className="rounded-xl" disabled={pay.isPending} onClick={()=>pay.mutate({id:order.id,amount:remaining,paymentMethod:method})}><CreditCard className="mr-2 h-4 w-4"/>Receber via {methodLabels[method]}</Button></article>})}</div>:<p className="py-12 text-center text-muted-foreground">Nenhum pagamento pendente.</p>}</CardContent></Card>
    <Card className="surface-elevated rounded-2xl"><CardHeader><CardTitle className="text-xl">Recebimentos recentes</CardTitle></CardHeader><CardContent>{recentPayments.length?<div className="space-y-3">{recentPayments.map(payment=><article key={payment.id} className="flex flex-col gap-2 rounded-2xl border p-4 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><strong>#{payment.orderId.slice(0,8)}</strong><Badge variant="secondary">{methodLabels[payment.method]??payment.method}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{payment.customer} · {new Date(payment.paid_at??payment.created_at).toLocaleString("pt-BR")}</p></div><strong className="text-lg text-emerald-700">{money.format(Number(payment.amount))}</strong></article>)}</div>:<p className="py-12 text-center text-muted-foreground">Nenhum recebimento registrado.</p>}</CardContent></Card>
  </div></div>;
}
