import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Megaphone, PauseCircle, PlayCircle, Wallet } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useOrganization } from "@/contexts/OrganizationContext";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Campaign={id:string;name:string;channel:string;status:string;budget:number;starts_at:string|null;ends_at:string|null;created_at:string};
const labels:Record<string,string>={draft:"Rascunho",active:"Ativa",paused:"Pausada",completed:"Concluída"};
export default function Marketing(){
  const {organizationId}=useOrganization();const queryClient=useQueryClient();const {toast}=useToast();
  const [name,setName]=useState("");const [channel,setChannel]=useState("whatsapp");const [budget,setBudget]=useState("0");const [start,setStart]=useState("");const [end,setEnd]=useState("");
  const campaigns=useQuery({queryKey:["campaigns",organizationId],enabled:Boolean(organizationId&&supabase),queryFn:async()=>{const {data,error}=await supabase!.from("marketing_campaigns").select("id,name,channel,status,budget,starts_at,ends_at,created_at").eq("organization_id",organizationId!).order("created_at",{ascending:false});if(error)throw error;return data as Campaign[];}});
  const create=useMutation({mutationFn:async()=>{const value=Number(budget.replace(",","."));if(!Number.isFinite(value)||value<0)throw new Error("invalid");const {error}=await supabase!.from("marketing_campaigns").insert({organization_id:organizationId,name:name.trim(),channel,budget:value,starts_at:start||null,ends_at:end||null});if(error)throw error;},onSuccess:async()=>{setName("");setBudget("0");setStart("");setEnd("");await queryClient.invalidateQueries({queryKey:["campaigns",organizationId]});toast({title:"Campanha criada"});},onError:()=>toast({title:"Campanha não criada",description:"Revise nome, orçamento e período.",variant:"destructive"})});
  const change=useMutation({mutationFn:async({id,status}:{id:string;status:string})=>{const {error}=await supabase!.from("marketing_campaigns").update({status}).eq("id",id).eq("organization_id",organizationId!);if(error)throw error;},onSuccess:()=>queryClient.invalidateQueries({queryKey:["campaigns",organizationId]}),onError:()=>toast({title:"Campanha não atualizada",variant:"destructive"})});
  const list=campaigns.data??[];const active=list.filter(i=>i.status==="active");const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
  return <div className="min-h-screen bg-background p-4 md:p-8 lg:p-10"><div className="mx-auto max-w-7xl space-y-7">
    <div><p className="text-sm font-semibold uppercase tracking-[.16em] text-primary">Relacionamento</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Marketing</h1><p className="mt-1 text-muted-foreground">Organize campanhas e acompanhe o orçamento planejado.</p></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Campanhas</p><strong className="mt-2 block text-2xl">{list.length}</strong></CardContent></Card><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Ativas</p><strong className="mt-2 block text-2xl text-emerald-700">{active.length}</strong></CardContent></Card><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Orçamento ativo</p><strong className="mt-2 block text-2xl">{money.format(active.reduce((s,i)=>s+Number(i.budget),0))}</strong></CardContent></Card></div>
    <Card className="surface-elevated rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2 text-xl"><Megaphone className="h-5 w-5 text-primary"/>Nova campanha</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2 xl:grid-cols-5" onSubmit={e=>{e.preventDefault();create.mutate();}}><div className="space-y-2 xl:col-span-2"><Label>Nome</Label><Input className="h-11 rounded-xl" value={name} onChange={e=>setName(e.target.value)} required minLength={2} placeholder="Combo do fim de semana"/></div><div className="space-y-2"><Label>Canal</Label><Select value={channel} onValueChange={setChannel}><SelectTrigger className="h-11 rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="whatsapp">WhatsApp</SelectItem><SelectItem value="instagram">Instagram</SelectItem><SelectItem value="email">E-mail</SelectItem><SelectItem value="other">Outro</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Orçamento</Label><Input className="h-11 rounded-xl" inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)}/></div><div className="space-y-2"><Label>Início</Label><Input className="h-11 rounded-xl" type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="space-y-2"><Label>Fim</Label><Input className="h-11 rounded-xl" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div><Button className="h-11 rounded-xl md:col-span-2 xl:col-span-4" disabled={create.isPending}>Criar rascunho</Button></form></CardContent></Card>
    <Card className="surface-elevated rounded-2xl"><CardHeader><CardTitle className="text-xl">Campanhas</CardTitle></CardHeader><CardContent>{campaigns.isLoading?<p className="py-12 text-center text-muted-foreground">Carregando…</p>:list.length?<div className="grid gap-3 lg:grid-cols-2">{list.map(item=><article key={item.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-sm capitalize text-muted-foreground">{item.channel} · {money.format(item.budget)}</p></div><Badge variant={item.status==="active"?"default":"outline"}>{labels[item.status]}</Badge></div><div className="mt-5 flex justify-end">{item.status!=="completed"&&(item.status==="active"?<Button variant="outline" className="rounded-xl" onClick={()=>change.mutate({id:item.id,status:"paused"})}><PauseCircle className="mr-2 h-4 w-4"/>Pausar</Button>:<Button className="rounded-xl" onClick={()=>change.mutate({id:item.id,status:"active"})}><PlayCircle className="mr-2 h-4 w-4"/>Ativar</Button>)}</div></article>)}</div>:<p className="py-12 text-center text-muted-foreground">Nenhuma campanha cadastrada.</p>}</CardContent></Card>
  </div></div>;
}
