import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, PackageCheck, ShoppingBasket, Truck } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useOrganization } from "@/contexts/OrganizationContext";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Supplier={id:string;name:string};
type Purchase={id:string;description:string;total:number;status:string;expected_at:string|null;created_at:string;suppliers:{name:string}|null};
const statusLabel:Record<string,string>={planned:"Planejada",ordered:"Solicitada",received:"Recebida",cancelled:"Cancelada"};

export default function Purchases(){
  const {organizationId}=useOrganization(); const queryClient=useQueryClient(); const {toast}=useToast();
  const [supplierName,setSupplierName]=useState(""); const [supplierId,setSupplierId]=useState("none");
  const [description,setDescription]=useState(""); const [total,setTotal]=useState(""); const [expected,setExpected]=useState("");
  const suppliers=useQuery({queryKey:["suppliers",organizationId],enabled:Boolean(organizationId&&supabase),queryFn:async()=>{const {data,error}=await supabase!.from("suppliers").select("id,name").eq("organization_id",organizationId!).eq("active",true).order("name");if(error)throw error;return data as Supplier[];}});
  const purchases=useQuery({queryKey:["purchases",organizationId],enabled:Boolean(organizationId&&supabase),queryFn:async()=>{const {data,error}=await supabase!.from("purchases").select("id,description,total,status,expected_at,created_at,suppliers(name)").eq("organization_id",organizationId!).order("created_at",{ascending:false});if(error)throw error;return data as unknown as Purchase[];}});
  const createSupplier=useMutation({mutationFn:async()=>{const {error}=await supabase!.from("suppliers").insert({organization_id:organizationId,name:supplierName.trim()});if(error)throw error;},onSuccess:async()=>{setSupplierName("");await queryClient.invalidateQueries({queryKey:["suppliers",organizationId]});toast({title:"Fornecedor cadastrado"});},onError:()=>toast({title:"Fornecedor não cadastrado",description:"Verifique se o nome já existe.",variant:"destructive"})});
  const createPurchase=useMutation({mutationFn:async()=>{const value=Number(total.replace(",","."));if(!Number.isFinite(value)||value<0)throw new Error("invalid");const {error}=await supabase!.from("purchases").insert({organization_id:organizationId,supplier_id:supplierId==="none"?null:supplierId,description:description.trim(),total:value,expected_at:expected||null});if(error)throw error;},onSuccess:async()=>{setDescription("");setTotal("");setExpected("");await queryClient.invalidateQueries({queryKey:["purchases",organizationId]});toast({title:"Compra planejada"});},onError:()=>toast({title:"Compra não cadastrada",description:"Revise a descrição e o valor.",variant:"destructive"})});
  const updateStatus=useMutation({mutationFn:async({id,status}:{id:string;status:string})=>{const {error}=await supabase!.from("purchases").update({status,received_at:status==="received"?new Date().toISOString():null}).eq("id",id).eq("organization_id",organizationId!);if(error)throw error;},onSuccess:()=>queryClient.invalidateQueries({queryKey:["purchases",organizationId]}),onError:()=>toast({title:"Status não atualizado",variant:"destructive"})});
  const list=purchases.data??[]; const pending=list.filter(item=>!["received","cancelled"].includes(item.status)); const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
  return <div className="min-h-screen bg-background p-4 md:p-8 lg:p-10"><div className="mx-auto max-w-7xl space-y-7">
    <div><p className="text-sm font-semibold uppercase tracking-[.16em] text-primary">Suprimentos</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Compras</h1><p className="mt-1 text-muted-foreground">Planeje reposições e acompanhe fornecedores e recebimentos.</p></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Fornecedores ativos</p><strong className="mt-2 block text-2xl">{suppliers.data?.length??0}</strong></CardContent></Card><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Compras pendentes</p><strong className="mt-2 block text-2xl">{pending.length}</strong></CardContent></Card><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Valor pendente</p><strong className="mt-2 block text-2xl">{money.format(pending.reduce((s,i)=>s+Number(i.total),0))}</strong></CardContent></Card></div>
    <div className="grid gap-5 lg:grid-cols-[.8fr_1.4fr]"><Card className="surface-elevated rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2 text-xl"><Truck className="h-5 w-5 text-primary"/>Novo fornecedor</CardTitle></CardHeader><CardContent><form className="flex gap-2" onSubmit={e=>{e.preventDefault();createSupplier.mutate();}}><Input className="h-11 rounded-xl" value={supplierName} onChange={e=>setSupplierName(e.target.value)} required minLength={2} placeholder="Nome do fornecedor"/><Button className="h-11 rounded-xl" disabled={createSupplier.isPending}>Salvar</Button></form></CardContent></Card>
    <Card className="surface-elevated rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2 text-xl"><ShoppingBasket className="h-5 w-5 text-primary"/>Nova compra</CardTitle></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" onSubmit={e=>{e.preventDefault();createPurchase.mutate();}}><div className="space-y-2"><Label>Descrição</Label><Input className="h-11 rounded-xl" value={description} onChange={e=>setDescription(e.target.value)} required minLength={2} placeholder="Reposição semanal"/></div><div className="space-y-2"><Label>Fornecedor</Label><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger className="h-11 rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sem fornecedor</SelectItem>{suppliers.data?.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Valor</Label><Input className="h-11 rounded-xl" inputMode="decimal" value={total} onChange={e=>setTotal(e.target.value)} required placeholder="0,00"/></div><div className="space-y-2"><Label>Previsão</Label><Input className="h-11 rounded-xl" type="date" value={expected} onChange={e=>setExpected(e.target.value)}/></div><Button className="h-11 rounded-xl sm:col-span-2 xl:col-span-4" disabled={createPurchase.isPending}>Planejar compra</Button></form></CardContent></Card></div>
    <Card className="surface-elevated rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2 text-xl"><PackageCheck className="h-5 w-5 text-primary"/>Histórico</CardTitle></CardHeader><CardContent>{purchases.isLoading?<p className="py-12 text-center text-muted-foreground">Carregando…</p>:list.length?<div className="space-y-3">{list.map(item=><article key={item.id} className="flex flex-col gap-4 rounded-2xl border p-4 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><strong>{item.description}</strong><Badge variant={item.status==="received"?"default":"outline"}>{statusLabel[item.status]}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.suppliers?.name??"Sem fornecedor"}{item.expected_at?` · previsão ${new Date(item.expected_at+"T12:00:00").toLocaleDateString("pt-BR")}`:""}</p></div><strong>{money.format(item.total)}</strong>{!["received","cancelled"].includes(item.status)&&<div className="flex gap-2">{item.status==="planned"&&<Button variant="outline" className="rounded-xl" onClick={()=>updateStatus.mutate({id:item.id,status:"ordered"})}>Solicitar</Button>}<Button className="rounded-xl" onClick={()=>updateStatus.mutate({id:item.id,status:"received"})}><CheckCircle2 className="mr-2 h-4 w-4"/>Receber</Button></div>}</article>)}</div>:<p className="py-12 text-center text-muted-foreground">Nenhuma compra cadastrada.</p>}</CardContent></Card>
  </div></div>;
}
