import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { MessageSquareHeart, Star } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useOrganization } from "@/contexts/OrganizationContext";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type Review={id:string;rating:number;comment:string|null;source:string;responded_at:string|null;created_at:string};
export default function Reviews(){
  const {organizationId}=useOrganization();const queryClient=useQueryClient();const {toast}=useToast();
  const [rating,setRating]=useState("5");const [source,setSource]=useState("direct");const [comment,setComment]=useState("");
  const reviews=useQuery({queryKey:["reviews",organizationId],enabled:Boolean(organizationId&&supabase),queryFn:async()=>{const {data,error}=await supabase!.from("reviews").select("id,rating,comment,source,responded_at,created_at").eq("organization_id",organizationId!).order("created_at",{ascending:false});if(error)throw error;return data as Review[];}});
  const create=useMutation({mutationFn:async()=>{const {error}=await supabase!.from("reviews").insert({organization_id:organizationId,rating:Number(rating),source,comment:comment.trim()||null});if(error)throw error;},onSuccess:async()=>{setRating("5");setComment("");await Promise.all([queryClient.invalidateQueries({queryKey:["reviews",organizationId]}),queryClient.invalidateQueries({queryKey:["business-dashboard",organizationId]})]);toast({title:"Avaliação registrada"});},onError:()=>toast({title:"Avaliação não registrada",variant:"destructive"})});
  const respond=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase!.from("reviews").update({responded_at:new Date().toISOString()}).eq("id",id).eq("organization_id",organizationId!);if(error)throw error;},onSuccess:()=>queryClient.invalidateQueries({queryKey:["reviews",organizationId]}),onError:()=>toast({title:"Avaliação não atualizada",variant:"destructive"})});
  const list=reviews.data??[];const average=list.length?list.reduce((s,i)=>s+Number(i.rating),0)/list.length:0;const pending=list.filter(i=>!i.responded_at).length;
  return <div className="min-h-screen bg-background p-4 md:p-8 lg:p-10"><div className="mx-auto max-w-7xl space-y-7">
    <div><p className="text-sm font-semibold uppercase tracking-[.16em] text-primary">Experiência</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Avaliações</h1><p className="mt-1 text-muted-foreground">Centralize feedbacks e acompanhe a satisfação dos clientes.</p></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Nota média</p><strong className="mt-2 flex items-center gap-2 text-2xl">{average.toFixed(1)}<Star className="h-5 w-5 fill-amber-400 text-amber-400"/></strong></CardContent></Card><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Avaliações</p><strong className="mt-2 block text-2xl">{list.length}</strong></CardContent></Card><Card className="surface-elevated rounded-2xl"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Aguardando retorno</p><strong className="mt-2 block text-2xl">{pending}</strong></CardContent></Card></div>
    <Card className="surface-elevated rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2 text-xl"><MessageSquareHeart className="h-5 w-5 text-primary"/>Registrar feedback</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-[.5fr_.7fr_2fr_auto]" onSubmit={e=>{e.preventDefault();create.mutate();}}><div className="space-y-2"><Label>Nota</Label><Select value={rating} onValueChange={setRating}><SelectTrigger className="h-11 rounded-xl"><SelectValue/></SelectTrigger><SelectContent>{[5,4,3,2,1].map(value=><SelectItem key={value} value={String(value)}>{value} estrelas</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Origem</Label><Select value={source} onValueChange={setSource}><SelectTrigger className="h-11 rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="direct">Direto</SelectItem><SelectItem value="google">Google</SelectItem><SelectItem value="instagram">Instagram</SelectItem><SelectItem value="ifood">iFood</SelectItem><SelectItem value="other">Outro</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Comentário</Label><Textarea className="min-h-11 rounded-xl" value={comment} onChange={e=>setComment(e.target.value)} placeholder="O que o cliente disse?"/></div><Button className="h-11 self-end rounded-xl" disabled={create.isPending}>Registrar</Button></form></CardContent></Card>
    <Card className="surface-elevated rounded-2xl"><CardHeader><CardTitle className="text-xl">Feedbacks recentes</CardTitle></CardHeader><CardContent>{reviews.isLoading?<p className="py-12 text-center text-muted-foreground">Carregando…</p>:list.length?<div className="space-y-3">{list.map(item=><article key={item.id} className="flex flex-col gap-4 rounded-2xl border p-4 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><span className="flex">{Array.from({length:5},(_,i)=><Star key={i} className={`h-4 w-4 ${i<item.rating?"fill-amber-400 text-amber-400":"text-muted"}`}/>)}</span><Badge variant="outline" className="capitalize">{item.source}</Badge>{item.responded_at&&<Badge>Respondida</Badge>}</div><p className="mt-2 text-sm">{item.comment||"Sem comentário."}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString("pt-BR")}</p></div>{!item.responded_at&&<Button variant="outline" className="rounded-xl" onClick={()=>respond.mutate(item.id)}>Marcar retorno</Button>}</article>)}</div>:<p className="py-12 text-center text-muted-foreground">Nenhuma avaliação registrada.</p>}</CardContent></Card>
  </div></div>;
}
